export const ROUTE_NAME = {
  LOGIN_PAGE: "/login",
  FORGET_PASSWORD: "/forget-password",
  HOME: "/",
  DASHBOARD: "/dashboard",
  GRADES: "/school/grades",
  CLASSROOM: "/school/classroom",
  EXAMS: "/school/exams",
  ATTANDANCE: "/class/attandance",
  ANNOUNCEMENTS: "/school/announcements",
  CREATE_ANNOUNCEMENTS: "/school/announcements/new",
  TEACHERS: "/school/teachers",
  ADD_TEACHER: "/school/teachers/register",
  INVITATION_TEACHER: "/invitation/teacher/new",
  REGISTRATION: "/school/register",
  STUDENTS: "/school/students",
  SETTING: "/school/setting",
  STUDENT_PROFILE: "/school/students/profile/:id",
  ADD_STUDENT: "/school/students/register",
  TEACHER_PROFILE: "/school/teachers/profile/:id",
};
