export const ADD_TOURNAMENT = "ADD_TOURNAMENT";
export const ADD_FORM_DATA = "ADD_FORM_DATA";
export const DELETE_TOURNAMENT = "DELETE_TOURNAMENT";
export const ADD_TOURNAMENT_REDUX_FORM = "ADD_TOURNAMENT_REDUX_FORM";
export const EDIT_TOURNAMENT_REDUX_FORM = "EDIT_TOURNAMENT_REDUX_FORM";
